### ISSUE TITLE
Fatal error on SignUp

### ISSUE THREAD

**Issue by ghost** [BruceBuckland/SignIn-awsmhh#3]
Fatal error raised on SignUp right after validation using SignUp button:
`fatal error: unexpectedly found nil while unwrapping an Optional value`

Crashed occured on `SignupViewController:signupPressed` on `signUp` call:

```
self.pool!.signUp(usernameField.text!, password: passwordField.text!, userAttributes: attributes, validationData: nil).continueWithBlock{ (task) in
```

All parameters are populated:
- `usernameField`
- `passwordField`
- `userAttributes`, with `email` only

I hard-coded these values to bypass eventual problems with form fields.

**Comment by BruceBuckland** [comment]
@Domsware  Yes .. Thanks!
  I have been testing with the same user pool and it turns out that when logging in the pool get's instantiated.  But if you start the app, and then signup (never having logged in with an existing ID), the pool is not yet instantiated.

I need to set up a test suite (now that I finally understand how Cognito and CognitoUserPools works.

This can happen in forgot password, and in signup.
I will push a new version that contains the fix (in 30 minutes or so)
(basically the fix is for this is:  replace this line (approx line 60)

```
        self.pool = AWSCognitoIdentityUserPool(forKey: "UserPool")
```

with these lines:

```
        let customSignInProvider = AWSCUPIdPSignInProvider.sharedInstance
        customSignInProvider.configureIdentityManager()
        self.pool = customSignInProvider.pool
```

**Comment by ghost** [comment]
Ok, this work now. Thanks.
